version: '3'

services:
  helk-elasticsearch:
    build: helk-elasticsearch/
    container_name: helk-elasticsearch
    volumes:
      - ./helk-elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    networks:
      helk:
        aliases:
          - helk_elasticsearch.hunt.local
  helk-logstash:
    build: helk-logstash/
    container_name: helk-logstash
    volumes:
      - ./helk-logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./helk-logstash/pipeline:/usr/share/logstash/pipeline
      - ./helk-logstash/cti:/usr/share/logstash/cti
    environment:
      - "LS_JAVA_OPTS=-Xms2g -Xmx2g"
    restart: always
    depends_on:
      - helk-elasticsearch
    networks:
      helk:
        aliases:
          - helk_logstash.hunt.local
  helk-kibana:
    build: helk-kibana/
    container_name: helk-kibana
    volumes:
      - ./helk-kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./helk-kibana/dashboards:/usr/share/kibana/dashboards
    restart: always
    depends_on:
      - helk-elasticsearch
    networks:
      helk:
        aliases:
          - helk_kibana.hunt.local
  helk-nginx:
    build: helk-nginx/
    container_name: helk-nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - helk-kibana
    networks:
      helk:
        aliases:
          - helk_nginx.hunt.local

networks:
  helk:
    driver: bridge
  
